# Generated by Django 5.2.6 on 2025-09-09 15:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the equipment sale', max_length=200)),
                ('vendor', models.CharField(blank=True, help_text='Vendor name (optional)', max_length=200)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of equipment to be sold', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total dollar amount for the sale', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('project_start_date', models.DateField(help_text='Date when the project commences (day 0 for milestone calculations)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone_structure', models.ForeignKey(help_text='Payment milestone structure to use for this sale', on_delete=django.db.models.deletion.CASCADE, to='milestones.paymentmilestonestructure')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
