# Generated by Django 5.2.6 on 2025-09-10 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsale',
            name='milestone_structure',
            field=models.ForeignKey(blank=True, help_text='Payment milestone structure to use for this sale (can be assigned later)', null=True, on_delete=django.db.models.deletion.CASCADE, to='milestones.paymentmilestonestructure'),
        ),
    ]
