# Generated by Django 5.2.6 on 2025-09-09 15:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMilestoneStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for this milestone structure', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this milestone structure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of this milestone (e.g., 'Down Payment', 'Final Payment')", max_length=100)),
                ('payment_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of total payment due (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('net_terms_days', models.PositiveIntegerField(default=0, help_text='Number of days after milestone due date for payment terms')),
                ('days_after_previous', models.PositiveIntegerField(default=0, help_text='Days after previous milestone (0 for first milestone)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this milestone within the structure')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='milestones.paymentmilestonestructure')),
            ],
            options={
                'ordering': ['structure', 'order'],
                'unique_together': {('structure', 'order')},
            },
        ),
    ]
